services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  server:
    build:
      context: .
    environment:
      REDIS_HOST: redis
      NODE_ENV: production
    depends_on:
      - redis
    ports:
      - "3000"